/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=../../.env.example --include-runtime=false` (hash: c820967128417890ce089395ba89ca6f)
interface __BaseEnv_Env {
	BRAIN_FILES: R2Bucket;
	FILES: R2Bucket;
	EXECUTOR_BLOBS: R2Bucket;
	EXECUTOR_DB: D1Database;
	HYPERDRIVE: Hyperdrive;
	LOADER: WorkerLoader;
	BROWSER: BrowserRun;
	AI: Ai;
	SANDBOX_TRANSPORT: "rpc";
	SANDBOX_LOG_LEVEL: "warn";
	GARDEN_LOG_LEVEL: "warn";
	GARDEN_OFFLINE: "";
	GARDEN_MODEL_PROVIDER: "";
	GARDEN_MODEL_BASE_URL: "";
	GARDEN_MODEL_ID: "";
	GARDEN_MODEL_API_KEY: "";
	GARDEN_MODEL_CONTEXT_WINDOW_TOKENS: "";
	GITHUB_CLIENT_ID: "";
	GITHUB_CLIENT_SECRET: "";
	GITHUB_APP_ID: "";
	GITHUB_APP_SLUG: "";
	GITHUB_APP_PRIVATE_KEY: "";
	GITHUB_WEBHOOK_SECRET: "";
	GOOGLE_CLIENT_ID: "";
	GOOGLE_CLIENT_SECRET: "";
	SLACK_CLIENT_ID: "";
	SLACK_CLIENT_SECRET: "";
	DISCORD_CLIENT_ID: "";
	DISCORD_CLIENT_SECRET: "";
	DISCORD_BOT_TOKEN: "";
	DISCORD_PUBLIC_KEY: "";
	DISCORD_BOT_PERMISSIONS: "";
	RESEND_API_KEY: "";
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	DATABASE_URL: string;
	ENVIRONMENT: string;
	EXECUTOR_SECRET_KEY: string;
	GOOGLE_AUTH_CLIENT_ID: string;
	GOOGLE_AUTH_CLIENT_SECRET: string;
	HELIX_URL: string;
	HELIX_API_KEY: string;
	AgentDO: DurableObjectNamespace<import("./src/server").AgentDO>;
	Sandbox: DurableObjectNamespace<import("./src/server").Sandbox>;
	AUTOMATION_TRIGGER: DurableObjectNamespace<import("./src/server").AutomationTriggerDO>;
	EXECUTOR_MCP_SESSION: DurableObjectNamespace<import("./src/server").ExecutorMcpSession>;
	EXECUTOR_MCP_EXECUTION_OWNER: DurableObjectNamespace<import("./src/server").ExecutorMcpExecutionOwnerDirectory>;
	RUN_WORKFLOW: Workflow<Parameters<import("./src/server").RunWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Sandbox" | "AgentDO" | "ChatSubAgent" | "IssueRunSubAgent" | "AutomationTriggerDO" | "ExecutorMcpSession" | "ExecutorMcpExecutionOwnerDirectory";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SANDBOX_TRANSPORT" | "SANDBOX_LOG_LEVEL" | "GARDEN_LOG_LEVEL" | "GARDEN_OFFLINE" | "GARDEN_MODEL_PROVIDER" | "GARDEN_MODEL_BASE_URL" | "GARDEN_MODEL_ID" | "GARDEN_MODEL_API_KEY" | "GARDEN_MODEL_CONTEXT_WINDOW_TOKENS" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "GITHUB_APP_ID" | "GITHUB_APP_SLUG" | "GITHUB_APP_PRIVATE_KEY" | "GITHUB_WEBHOOK_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "SLACK_CLIENT_ID" | "SLACK_CLIENT_SECRET" | "DISCORD_CLIENT_ID" | "DISCORD_CLIENT_SECRET" | "DISCORD_BOT_TOKEN" | "DISCORD_PUBLIC_KEY" | "DISCORD_BOT_PERMISSIONS" | "RESEND_API_KEY" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "DATABASE_URL" | "ENVIRONMENT" | "EXECUTOR_SECRET_KEY" | "GOOGLE_AUTH_CLIENT_ID" | "GOOGLE_AUTH_CLIENT_SECRET" | "HELIX_URL" | "HELIX_API_KEY">> {}
}
